name: quiz_generator
description: "EduTech Quiz Generator app"
publish_to: 'none'

version: 0.1.1

environment:
  sdk: ^3.9.2
  flutter: '>=3.29.0 <3.35.5'

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  dropdown_button2: ^2.3.9
  http: ^1.5.0
  http_parser: ^4.1.2
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  riverpod_lint: ^3.0.3
  adaptive_dialog: ^2.5.0
  dio: ^5.9.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/favicon/Exam Portal Logo.png"

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz_wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz_wght.ttf
          style: italic
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic

  uses-material-design: true
  assets:
    - assets/favicon/
    - assets/icons/
    - assets/images/
    # flutter_dotenv package requires whichever .env (or any such file) be made an
    # asset here, so that I will show up in the app's private storage
    # you can also add .env.<whatnot>, etc, then load it with `dotenv.load('.env.<whatnot>')
    # DO NOT REMOVE OR YOU RISK BREAKING THE APP LAUNCH
    - .env
