name: Confirm Build

env:
  app_name: edutech-quizgenerator.apk

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV

      - name: Install Java SDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Install Android NDK r27
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27
          link-to-sdk: true
          local-cache: true

      - name: Install Flutter and Dart SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: "Build release package"
        run: |
          echo export MOCK_API_KEY='${{ env.MOCK_API_KEY }}' >> .env
          echo export EDUTECH_SWAGGER_URL='${{ env.EDUTECH_SWAGGER_URL }}' >> .env
          flutter build apk --release
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Prepare the release
        run: |
          cp build/app/outputs/apk/release/app-release.apk build/${{ env.app_name }}
          echo Renamed
          d="$(date)"
          echo "app_version=$d" >> $GITHUB_ENV
          echo "release of ${{ env.app_name }} on $d" > RELEASE.txt
          echo Generated RELEASE.txt

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.app_name }}-${{ env.app_version }}
          draft: true
          body_path: RELEASE.txt
          files: |
            build/${{ env.app_name }}
