name: Confirm Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - run: flutter build apk --release
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          name: edutech-quizgenerator.apk
          draft: true
          body: |
            This is seriously acting -- Sia noooo
          files: |
            build/app/outputs/apk/release/app-release.apk
