name: Confirm Build

env:
  app_name: edutech-quizgenerator.apk

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  rapid:
    runs-on: ubuntu-latest
    steps:
      - name: Rapid
        run: |
          echo ${{ vars.RAPID0 }}
